"""
Automated test suite for the myflames Python package.

Covers:
  - Parser unit tests (TestParser)
  - SVG output integration tests for all 4 renderers (TestOutputs)
  - CLI subprocess integration tests (TestCLI)

Fixture discovery:
  - test/fixtures/explain-*.json  (generated by scripts/generate-fixtures.sh)
  - test/mysql-explain-*.json     (hand-crafted originals)

Run:
  python3 -m unittest test.test_myflames -v
  python3 -m unittest discover -s test -p "test_myflames.py" -v
"""
import glob
import json
import os
import subprocess
import sys
import unittest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(TEST_DIR)

# Hand-crafted fixtures shipped with the repo
BUILTIN_FIXTURES = sorted(glob.glob(os.path.join(TEST_DIR, "mysql-explain-*.json")))

# Generated fixtures (may not exist until generate-fixtures.sh is run)
GENERATED_FIXTURES = sorted(glob.glob(os.path.join(TEST_DIR, "fixtures", "explain-*.json")))

ALL_FIXTURES = BUILTIN_FIXTURES + GENERATED_FIXTURES

# ---------------------------------------------------------------------------
# Import myflames (must be importable from repo root)
# ---------------------------------------------------------------------------

sys.path.insert(0, REPO_DIR)

from myflames.parser import (
    parse_explain,
    flatten_nodes,
    build_flame_entries,
    analyze_plan,
    render_analysis_panel,
    render_info_panel,
)
from myflames.output_bargraph import render_bargraph
from myflames.output_treemap import render_treemap
from myflames.output_diagram import render_diagram


def _load(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def _tree_depth(node, depth=1):
    if not node.get("children"):
        return depth
    return max(_tree_depth(c, depth + 1) for c in node["children"])


def _is_valid_svg(text):
    """Returns True if text looks like a well-formed SVG document."""
    stripped = text.strip()
    return (
        stripped.startswith("<?xml") or stripped.startswith("<svg")
    ) and "</svg>" in stripped


# ---------------------------------------------------------------------------
# TestParser — unit tests for parser.py
# ---------------------------------------------------------------------------

class TestParser(unittest.TestCase):
    """Unit tests for parse_explain and helper functions."""

    @classmethod
    def setUpClass(cls):
        sample = os.path.join(TEST_DIR, "mysql-explain-json-sample.json")
        join = os.path.join(TEST_DIR, "mysql-explain-json-join.json")
        complex_ = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")
        cls.sample_text = _load(sample)
        cls.join_text = _load(join)
        cls.complex_text = _load(complex_)

    def test_parse_simple_returns_root(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root, dict)

    def test_parse_simple_has_positive_total_time(self):
        root = parse_explain(self.sample_text)
        self.assertGreater(root["total_time"], 0)

    def test_parse_simple_has_folded_label(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root["folded_label"], str)
        self.assertTrue(root["folded_label"].strip())

    def test_parse_simple_children_list(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root["children"], list)

    def test_parse_join_has_children(self):
        root = parse_explain(self.join_text)
        self.assertGreater(len(root.get("children", [])), 0)

    def test_parse_complex_depth_at_least_2(self):
        root = parse_explain(self.complex_text)
        self.assertGreaterEqual(_tree_depth(root), 2)

    def test_self_time_nonnegative_all_nodes(self):
        for text in (self.sample_text, self.join_text, self.complex_text):
            root = parse_explain(text)
            for node in flatten_nodes(root):
                with self.subTest(label=node["folded_label"]):
                    self.assertGreaterEqual(node["self_time"], 0)

    def test_total_time_ge_self_time(self):
        for text in (self.sample_text, self.join_text, self.complex_text):
            root = parse_explain(text)
            for node in flatten_nodes(root):
                with self.subTest(label=node["folded_label"]):
                    self.assertGreaterEqual(
                        round(node["total_time"], 9),
                        round(node["self_time"], 9),
                    )

    def test_build_flame_entries_yields_tuples(self):
        root = parse_explain(self.complex_text)
        entries = list(build_flame_entries(root))
        self.assertTrue(len(entries) > 0)
        for path, t in entries:
            self.assertIsInstance(path, list)
            self.assertIsInstance(t, float)
            self.assertGreater(len(path), 0)

    def test_invalid_json_raises(self):
        with self.assertRaises(Exception):
            parse_explain("not valid json {{{")

    def test_explain_prefix_stripped(self):
        """EXPLAIN: prefix output by some MySQL clients should be handled."""
        raw = self.sample_text.strip()
        prefixed = "EXPLAIN: " + raw
        root = parse_explain(prefixed)
        self.assertIsInstance(root, dict)
        self.assertGreater(root["total_time"], 0)

    def test_node_has_required_keys(self):
        root = parse_explain(self.sample_text)
        required = {"folded_label", "short_label", "full_label",
                    "self_time", "total_time", "children", "details"}
        for node in flatten_nodes(root):
            with self.subTest(label=node.get("folded_label")):
                self.assertTrue(required.issubset(node.keys()))


# ---------------------------------------------------------------------------
# TestOutputs — integration tests for all 4 renderers
# ---------------------------------------------------------------------------

def _make_output_test(fixture_path, renderer_name):
    """Factory: returns a test method for one (fixture, renderer) pair."""
    def test_method(self):
        text = _load(fixture_path)
        root = parse_explain(text)
        fname = os.path.basename(fixture_path)

        if renderer_name == "flamegraph":
            from myflames.flamegraph import folded_to_svg
            entries = list(build_flame_entries(root))
            lines = []
            for path, t in entries:
                ms = int(t * 1000 + 0.5)
                ms = max(ms, 1) if len(path) == 1 else ms
                if ms > 0:
                    lines.append(";".join(path) + " " + str(ms))
            if not lines:
                self.skipTest(f"{fname}: all-zero self-time, no flamegraph data")
            svg = folded_to_svg("\n".join(lines), title="Test")
        elif renderer_name == "bargraph":
            svg = render_bargraph(root)
        elif renderer_name == "treemap":
            svg = render_treemap(root)
        elif renderer_name == "diagram":
            svg = render_diagram(root)
        else:
            self.fail(f"Unknown renderer: {renderer_name}")

        self.assertIsInstance(svg, str, f"{fname}/{renderer_name}: expected str output")
        self.assertTrue(svg.strip(), f"{fname}/{renderer_name}: output is empty")
        self.assertTrue(
            _is_valid_svg(svg),
            f"{fname}/{renderer_name}: output is not valid SVG\n"
            f"(starts with: {svg[:80]!r})",
        )

    test_method.__name__ = (
        f"test_{renderer_name}_{os.path.basename(fixture_path).replace('-', '_').replace('.json', '')}"
    )
    test_method.__doc__ = f"{renderer_name} on {os.path.basename(fixture_path)}"
    return test_method


class TestOutputsMeta(type):
    """Metaclass that dynamically generates test methods for all fixture × renderer combos."""

    def __new__(mcs, name, bases, namespace):
        cls = super().__new__(mcs, name, bases, namespace)
        renderers = ["flamegraph", "bargraph", "treemap", "diagram"]
        for fixture in ALL_FIXTURES:
            for renderer in renderers:
                method = _make_output_test(fixture, renderer)
                # Ensure unique method name (truncate if very long)
                method_name = method.__name__[:120]
                setattr(cls, method_name, method)
        return cls


class TestOutputs(unittest.TestCase, metaclass=TestOutputsMeta):
    """
    SVG output tests for all renderers against all fixture files.

    Test methods are generated dynamically: one per (fixture, renderer) pair.
    With 3 builtin fixtures × 4 renderers = 12 baseline tests;
    generated fixtures add more proportionally.
    """


# ---------------------------------------------------------------------------
# TestCLI — subprocess tests for the CLI entry point
# ---------------------------------------------------------------------------

class TestCLI(unittest.TestCase):
    """Subprocess-level tests for `python3 -m myflames`."""

    PYTHON = sys.executable
    SAMPLE = os.path.join(TEST_DIR, "mysql-explain-json-sample.json")
    JOIN = os.path.join(TEST_DIR, "mysql-explain-json-join.json")
    COMPLEX = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")

    def _run(self, *args, input_text=None):
        cmd = [self.PYTHON, "-m", "myflames"] + list(args)
        result = subprocess.run(
            cmd,
            input=input_text,
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        return result

    def _assert_valid_svg_output(self, result, label=""):
        self.assertEqual(
            result.returncode, 0,
            f"{label}: exit code {result.returncode}\nstderr: {result.stderr}",
        )
        self.assertTrue(
            _is_valid_svg(result.stdout),
            f"{label}: stdout is not valid SVG\n"
            f"(starts with: {result.stdout[:80]!r})",
        )

    def test_flamegraph_default(self):
        r = self._run(self.SAMPLE)
        self._assert_valid_svg_output(r, "flamegraph default")

    def test_bargraph_type(self):
        r = self._run("--type", "bargraph", self.JOIN)
        self._assert_valid_svg_output(r, "bargraph")

    def test_treemap_type(self):
        r = self._run("--type", "treemap", self.COMPLEX)
        self._assert_valid_svg_output(r, "treemap")

    def test_diagram_type(self):
        r = self._run("--type", "diagram", self.COMPLEX)
        self._assert_valid_svg_output(r, "diagram")

    def test_diagram_graphviz_engine_fallback(self):
        """--diagram-engine graphviz must not crash even if dot is not installed."""
        r = self._run("--type", "diagram", "--diagram-engine", "graphviz", self.COMPLEX)
        self._assert_valid_svg_output(r, "diagram graphviz fallback")

    def test_stdin_input(self):
        with open(self.SAMPLE, encoding="utf-8") as f:
            content = f.read()
        r = self._run("-", input_text=content)
        self._assert_valid_svg_output(r, "stdin input")

    def test_invalid_file_exits_nonzero(self):
        r = self._run("/nonexistent/path/to/explain.json")
        self.assertNotEqual(r.returncode, 0)

    def test_invalid_json_exits_nonzero(self):
        r = self._run("-", input_text="not valid json")
        self.assertNotEqual(r.returncode, 0)

    def test_title_option(self):
        r = self._run("--title", "My Custom Title", "--type", "bargraph", self.SAMPLE)
        self._assert_valid_svg_output(r, "custom title")
        self.assertIn("My Custom Title", r.stdout)

    def test_inverted_flag(self):
        r = self._run("--inverted", self.SAMPLE)
        self._assert_valid_svg_output(r, "inverted flamegraph")

    def test_width_option(self):
        r = self._run("--width", "800", "--type", "bargraph", self.SAMPLE)
        self._assert_valid_svg_output(r, "custom width")

    def test_all_fixtures_flamegraph(self):
        """All discovered fixtures must produce a valid flamegraph without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run(fixture)
                # Some fixtures may have all-zero self-time; tolerate exit 1 with specific stderr
                if r.returncode != 0:
                    self.assertIn(
                        "all zero self-time",
                        r.stderr.lower(),
                        f"Unexpected failure for {fixture}:\n{r.stderr}",
                    )
                else:
                    self.assertTrue(_is_valid_svg(r.stdout))

    def test_all_fixtures_bargraph(self):
        """All discovered fixtures must produce a valid bargraph without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run("--type", "bargraph", fixture)
                self.assertEqual(r.returncode, 0, f"stderr: {r.stderr}")
                self.assertTrue(_is_valid_svg(r.stdout))

    def test_all_fixtures_diagram(self):
        """All discovered fixtures must produce a valid diagram without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run("--type", "diagram", fixture)
                self.assertEqual(r.returncode, 0, f"stderr: {r.stderr}")
                self.assertTrue(_is_valid_svg(r.stdout))


# ---------------------------------------------------------------------------
# TestAnalysis — unit tests for analyze_plan() and render_analysis_panel()
# ---------------------------------------------------------------------------

class TestAnalysis(unittest.TestCase):
    """Tests for the plan analysis functions."""

    HASH_JOIN = os.path.join(TEST_DIR, "mysql-explain-hash-join.json")
    TABLE_SCAN = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
    MATERIALIZE = os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")
    COMPLEX = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")

    def _analyze(self, path):
        root = parse_explain(_load(path))
        return root, analyze_plan(root)

    # --- analyze_plan: hash join detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_detected(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertGreater(len(a["hash_joins"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_feature_flag(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("hash_join" in f for f in a["optimizer_features"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_warning_present(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("hash join" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_suggestion_present(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("join_buffer_size" in s for s in a["suggestions"]))

    # --- analyze_plan: full table scan detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_detected(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertGreater(len(a["full_scans"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_has_table_name(self):
        _, a = self._analyze(self.TABLE_SCAN)
        for s in a["full_scans"]:
            self.assertIn("table", s)
            self.assertTrue(s["table"])

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_warning_present(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertTrue(any("full table scan" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_suggestion_present(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertTrue(len(a["suggestions"]) > 0)

    # --- analyze_plan: temp table (Materialize) detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_detected(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertGreater(len(a["temp_tables"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_warning_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("temp table" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_suggestion_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("tmp_table_size" in s for s in a["suggestions"]))

    # --- analyze_plan: filesort detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_detected(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertGreater(len(a["filesorts"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_warning_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("sort" in w.lower() for w in a["warnings"]))

    # --- analyze_plan: nested loop / ICP features ---

    def test_nested_loop_feature_complex(self):
        _, a = self._analyze(self.COMPLEX)
        # complex join fixture uses nested loop joins
        features = a["optimizer_features"]
        # At least some features should be detected
        self.assertIsInstance(features, list)

    def test_icp_detection_when_pushed_index_condition(self):
        """Plans with pushed_index_condition should report ICP=on."""
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-035-join-2t-users-orders.json"))
        # This fixture has pushed_index_condition so ICP should appear
        features = a["optimizer_features"]
        self.assertTrue(any("index_condition_pushdown" in f for f in features))

    # --- analyze_plan: return structure ---

    def test_analyze_plan_returns_required_keys(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for key in ("full_scans", "hash_joins", "temp_tables", "filesorts",
                    "optimizer_features", "warnings", "suggestions", "node_highlights"):
            self.assertIn(key, a, f"Missing key: {key}")

    def test_analyze_plan_lists_are_lists(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for key in ("full_scans", "hash_joins", "temp_tables", "filesorts",
                    "optimizer_features", "warnings", "suggestions", "node_highlights"):
            self.assertIsInstance(a[key], list, f"{key} should be a list")

    def test_analyze_plan_strings_are_strings(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for w in a["warnings"]:
            self.assertIsInstance(w, str)
        for s in a["suggestions"]:
            self.assertIsInstance(s, str)
        for f in a["optimizer_features"]:
            self.assertIsInstance(f, str)

    def test_node_highlights_have_short_label_and_message(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for h in a["node_highlights"]:
            self.assertIn("short_label", h)
            self.assertIn("message", h)
            self.assertIsInstance(h["short_label"], str)
            self.assertIsInstance(h["message"], str)

    # --- render_analysis_panel ---

    def test_render_analysis_panel_returns_tuple(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        result = render_analysis_panel(a, 0, 0, 1200)
        self.assertIsInstance(result, tuple)
        self.assertEqual(len(result), 2)

    def test_render_analysis_panel_lines_are_strings(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, h = render_analysis_panel(a, 0, 0, 1200)
        self.assertIsInstance(lines, list)
        for line in lines:
            self.assertIsInstance(line, str)

    def test_render_analysis_panel_positive_height(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        _, h = render_analysis_panel(a, 0, 0, 1200)
        self.assertGreater(h, 0)

    def test_render_analysis_panel_contains_rect(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, _ = render_analysis_panel(a, 10, 100, 800)
        svg = "\n".join(lines)
        self.assertIn("<rect", svg)
        self.assertIn("<text", svg)

    def test_render_info_panel_single_block(self):
        """Consolidated panel contains both 'How to read' and 'Query Analysis'."""
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, h = render_info_panel(a, 0, 0, 800, view_type="bargraph")
        svg = "\n".join(lines)
        self.assertIn("How to read", svg)
        self.assertIn("Query Analysis", svg)
        self.assertGreater(h, 0)

    # --- Renderer integration: analysis panel in SVG output ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_treemap_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_bargraph_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_diagram_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_treemap_shows_warning(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertIn("hash join", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_bargraph_shows_warning(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertIn("hash join", svg.lower())

    # --- full_scans / hash_joins structure ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_entries_have_rows_and_loops(self):
        _, a = self._analyze(self.TABLE_SCAN)
        for s in a["full_scans"]:
            self.assertIn("rows", s)
            self.assertIn("loops", s)
            self.assertIsInstance(s["rows"], (int, float))
            self.assertIsInstance(s["loops"], int)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_entries_have_rows(self):
        _, a = self._analyze(self.HASH_JOIN)
        for h in a["hash_joins"]:
            self.assertIn("rows", h)
            self.assertIsInstance(h["rows"], (int, float))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_plan_has_two_full_scans(self):
        """Hash join fixture has table scan on users and on orders."""
        _, a = self._analyze(self.HASH_JOIN)
        tables = {s["table"] for s in a["full_scans"]}
        self.assertIn("users", tables)
        self.assertIn("orders", tables)
        self.assertGreaterEqual(len(a["full_scans"]), 2)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_entries_have_rows(self):
        _, a = self._analyze(self.MATERIALIZE)
        for t in a["temp_tables"]:
            self.assertIn("rows", t)
            self.assertIsInstance(t["rows"], (int, float))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_entries_have_rows(self):
        _, a = self._analyze(self.MATERIALIZE)
        for f in a["filesorts"]:
            self.assertIn("rows", f)
            self.assertIsInstance(f["rows"], (int, float))

    # --- optimizer_features: covering, semijoin, antijoin ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-016-covering-index-cat-price.json")), "fixture missing")
    def test_covering_index_feature_detected(self):
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-016-covering-index-cat-price.json"))
        self.assertTrue(
            any("covering" in f.lower() or "index_extensions" in f for f in a["optimizer_features"]),
            f"Expected covering/index_extensions in {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-047-semi-join-users-with-orders.json")), "fixture missing")
    def test_semijoin_fixture_analyzed_with_features(self):
        """Semijoin plan (Nested loop + Materialize) produces analysis with at least one feature (e.g. nested_loop, ICP)."""
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-047-semi-join-users-with-orders.json"))
        self.assertIsInstance(a["optimizer_features"], list)
        # Fixture has nested loop and pushed_index_condition; semijoin is in SQL text not in operation string
        self.assertGreater(
            len(a["optimizer_features"]), 0,
            f"Expected at least one optimizer feature: {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-050-anti-join-users-no-orders.json")), "fixture missing")
    def test_antijoin_feature_detected(self):
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-050-anti-join-users-no-orders.json"))
        self.assertTrue(
            any("antijoin" in f.lower() for f in a["optimizer_features"]),
            f"Expected antijoin in {a['optimizer_features']}",
        )

    # --- render_analysis_panel edge cases ---

    def test_render_analysis_panel_empty_analysis(self):
        """Panel with no features/warnings/suggestions still renders 'None detected' and valid SVG."""
        a = {
            "full_scans": [],
            "hash_joins": [],
            "temp_tables": [],
            "filesorts": [],
            "optimizer_features": [],
            "warnings": [],
            "suggestions": [],
        }
        lines, h = render_analysis_panel(a, 0, 0, 800)
        svg = "\n".join(lines)
        self.assertIn("Query Analysis", svg)
        self.assertIn("None detected", svg)
        self.assertGreater(h, 0)
        self.assertIn("<rect", svg)

    def test_render_analysis_panel_position_reflected_in_output(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, _ = render_analysis_panel(a, 100, 200, 600)
        svg = "\n".join(lines)
        self.assertIn('x="100"', svg)
        self.assertIn('y="200"', svg)

    # --- filesort suggestion text ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_suggestion_contains_sort_buffer_or_index(self):
        _, a = self._analyze(self.MATERIALIZE)
        suggestions_text = " ".join(a["suggestions"]).lower()
        self.assertTrue(
            "sort_buffer_size" in suggestions_text or "ordered index" in suggestions_text or "filesort" in suggestions_text,
            f"Expected sort_buffer_size or ordered index or filesort in suggestions: {a['suggestions']}",
        )

    # --- CLI: flamegraph includes Query Analysis panel ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_bargraph_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "bargraph", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_treemap_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "treemap", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_diagram_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "diagram", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_flamegraph_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "flamegraph", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_with_analysis_hash_join_shows_suggestion(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertIn("join_buffer_size", svg)

    # --- BNL (Block Nested Loop) detection ---

    BNL = os.path.join(TEST_DIR, "mysql-explain-bnl.json")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_detected(self):
        """BNL plan with using_join_buffer=Block Nested Loop and access_type=table is detected."""
        _, a = self._analyze(self.BNL)
        self.assertGreater(len(a["bnl_nodes"]), 0, "Expected BNL nodes in analysis")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_feature_flag(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("block_nested_loop" in f for f in a["optimizer_features"]),
            f"Expected block_nested_loop in optimizer_features: {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_warning_present(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("block nested" in w.lower() or "bnl" in w.lower() for w in a["warnings"]),
            f"Expected BNL warning: {a['warnings']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_suggestion_references_join_buffer_size(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("join_buffer_size" in s for s in a["suggestions"]),
            f"Expected join_buffer_size in suggestions: {a['suggestions']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_suggestion_mentions_hash_join_alternative(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("hash join" in s.lower() or "block_nested_loop" in s for s in a["suggestions"]),
            f"Expected hash join alternative mention in suggestions: {a['suggestions']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_node_highlight_created(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(len(a["node_highlights"]) > 0, "Expected node highlights for BNL nodes")
        for h in a["node_highlights"]:
            self.assertIn("short_label", h)
            self.assertIn("message", h)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_not_triggered_by_hash_join(self):
        """Hash join plan should not produce BNL detection."""
        _, a = self._analyze(self.HASH_JOIN)
        self.assertEqual(len(a["bnl_nodes"]), 0, "Hash join should not be flagged as BNL")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_bargraph_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertIn("block nested", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_treemap_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertIn("block nested", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_diagram_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertIn("block nested", svg.lower())


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    unittest.main(verbosity=2)
