"""
Automated test suite for the myflames Python package.

Covers:
  - Parser unit tests (TestParser)
  - SVG output integration tests for all 4 renderers (TestOutputs)
  - CLI subprocess integration tests (TestCLI)

Fixture discovery:
  - test/fixtures/explain-*.json  (generated by scripts/generate-fixtures.sh)
  - test/mysql-explain-*.json     (hand-crafted originals)

Run:
  python3 -m unittest test.test_myflames -v
  python3 -m unittest discover -s test -p "test_myflames.py" -v
"""
import glob
import json
import os
import subprocess
import sys
import unittest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(TEST_DIR)

# Hand-crafted fixtures shipped with the repo
BUILTIN_FIXTURES = sorted(glob.glob(os.path.join(TEST_DIR, "mysql-explain-*.json")))

# Generated fixtures (may not exist until generate-fixtures.sh is run)
GENERATED_FIXTURES = sorted(glob.glob(os.path.join(TEST_DIR, "fixtures", "explain-*.json")))

ALL_FIXTURES = BUILTIN_FIXTURES + GENERATED_FIXTURES

# ---------------------------------------------------------------------------
# Import myflames (must be importable from repo root)
# ---------------------------------------------------------------------------

sys.path.insert(0, REPO_DIR)

from myflames.parser import (
    parse_explain,
    flatten_nodes,
    build_flame_entries,
    analyze_plan,
    render_analysis_panel,
    render_info_panel,
    format_sql,
    _col_refs_for_table,
    _suggest_indexes,
)
from myflames.output_bargraph import render_bargraph
from myflames.output_treemap import render_treemap
from myflames.output_diagram import render_diagram
from myflames.output_tree import render_tree


def _load(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def _tree_depth(node, depth=1):
    if not node.get("children"):
        return depth
    return max(_tree_depth(c, depth + 1) for c in node["children"])


def _is_valid_svg(text):
    """Returns True if text looks like a well-formed SVG document."""
    stripped = text.strip()
    return (
        stripped.startswith("<?xml") or stripped.startswith("<svg")
    ) and "</svg>" in stripped


# ---------------------------------------------------------------------------
# TestParser — unit tests for parser.py
# ---------------------------------------------------------------------------

class TestParser(unittest.TestCase):
    """Unit tests for parse_explain and helper functions."""

    @classmethod
    def setUpClass(cls):
        sample = os.path.join(TEST_DIR, "mysql-explain-json-sample.json")
        join = os.path.join(TEST_DIR, "mysql-explain-json-join.json")
        complex_ = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")
        cls.sample_text = _load(sample)
        cls.join_text = _load(join)
        cls.complex_text = _load(complex_)

    def test_parse_simple_returns_root(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root, dict)

    def test_parse_simple_has_positive_total_time(self):
        root = parse_explain(self.sample_text)
        self.assertGreater(root["total_time"], 0)

    def test_parse_simple_has_folded_label(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root["folded_label"], str)
        self.assertTrue(root["folded_label"].strip())

    def test_parse_simple_children_list(self):
        root = parse_explain(self.sample_text)
        self.assertIsInstance(root["children"], list)

    def test_parse_join_has_children(self):
        root = parse_explain(self.join_text)
        self.assertGreater(len(root.get("children", [])), 0)

    def test_parse_complex_depth_at_least_2(self):
        root = parse_explain(self.complex_text)
        self.assertGreaterEqual(_tree_depth(root), 2)

    def test_self_time_nonnegative_all_nodes(self):
        for text in (self.sample_text, self.join_text, self.complex_text):
            root = parse_explain(text)
            for node in flatten_nodes(root):
                with self.subTest(label=node["folded_label"]):
                    self.assertGreaterEqual(node["self_time"], 0)

    def test_total_time_ge_self_time(self):
        for text in (self.sample_text, self.join_text, self.complex_text):
            root = parse_explain(text)
            for node in flatten_nodes(root):
                with self.subTest(label=node["folded_label"]):
                    self.assertGreaterEqual(
                        round(node["total_time"], 9),
                        round(node["self_time"], 9),
                    )

    def test_build_flame_entries_yields_tuples(self):
        root = parse_explain(self.complex_text)
        entries = list(build_flame_entries(root))
        self.assertTrue(len(entries) > 0)
        for path, t in entries:
            self.assertIsInstance(path, list)
            self.assertIsInstance(t, float)
            self.assertGreater(len(path), 0)

    def test_invalid_json_raises(self):
        with self.assertRaises(Exception):
            parse_explain("not valid json {{{")

    def test_explain_prefix_stripped(self):
        """EXPLAIN: prefix output by some MySQL clients should be handled."""
        raw = self.sample_text.strip()
        prefixed = "EXPLAIN: " + raw
        root = parse_explain(prefixed)
        self.assertIsInstance(root, dict)
        self.assertGreater(root["total_time"], 0)

    def test_node_has_required_keys(self):
        root = parse_explain(self.sample_text)
        required = {"folded_label", "short_label", "full_label",
                    "self_time", "total_time", "children", "details"}
        for node in flatten_nodes(root):
            with self.subTest(label=node.get("folded_label")):
                self.assertTrue(required.issubset(node.keys()))


# ---------------------------------------------------------------------------
# TestOutputs — integration tests for all 4 renderers
# ---------------------------------------------------------------------------

def _make_output_test(fixture_path, renderer_name):
    """Factory: returns a test method for one (fixture, renderer) pair."""
    def test_method(self):
        text = _load(fixture_path)
        root = parse_explain(text)
        fname = os.path.basename(fixture_path)

        if renderer_name == "flamegraph":
            from myflames.flamegraph import folded_to_svg
            entries = list(build_flame_entries(root))
            lines = []
            for path, t in entries:
                ms = int(t * 1000 + 0.5)
                ms = max(ms, 1) if len(path) == 1 else ms
                if ms > 0:
                    lines.append(";".join(path) + " " + str(ms))
            if not lines:
                self.skipTest(f"{fname}: all-zero self-time, no flamegraph data")
            svg = folded_to_svg("\n".join(lines), title="Test")
        elif renderer_name == "bargraph":
            svg = render_bargraph(root)
        elif renderer_name == "treemap":
            svg = render_treemap(root)
        elif renderer_name == "diagram":
            svg = render_diagram(root)
        elif renderer_name == "tree":
            svg = render_tree(root)
        else:
            self.fail(f"Unknown renderer: {renderer_name}")

        self.assertIsInstance(svg, str, f"{fname}/{renderer_name}: expected str output")
        self.assertTrue(svg.strip(), f"{fname}/{renderer_name}: output is empty")
        self.assertTrue(
            _is_valid_svg(svg),
            f"{fname}/{renderer_name}: output is not valid SVG\n"
            f"(starts with: {svg[:80]!r})",
        )

    test_method.__name__ = (
        f"test_{renderer_name}_{os.path.basename(fixture_path).replace('-', '_').replace('.json', '')}"
    )
    test_method.__doc__ = f"{renderer_name} on {os.path.basename(fixture_path)}"
    return test_method


class TestOutputsMeta(type):
    """Metaclass that dynamically generates test methods for all fixture × renderer combos."""

    def __new__(mcs, name, bases, namespace):
        cls = super().__new__(mcs, name, bases, namespace)
        renderers = ["flamegraph", "bargraph", "treemap", "diagram", "tree"]
        for fixture in ALL_FIXTURES:
            for renderer in renderers:
                method = _make_output_test(fixture, renderer)
                # Ensure unique method name (truncate if very long)
                method_name = method.__name__[:120]
                setattr(cls, method_name, method)
        return cls


class TestOutputs(unittest.TestCase, metaclass=TestOutputsMeta):
    """
    SVG output tests for all renderers against all fixture files.

    Test methods are generated dynamically: one per (fixture, renderer) pair.
    With 3 builtin fixtures × 4 renderers = 12 baseline tests;
    generated fixtures add more proportionally.
    """


# ---------------------------------------------------------------------------
# TestCLI — subprocess tests for the CLI entry point
# ---------------------------------------------------------------------------

class TestCLI(unittest.TestCase):
    """Subprocess-level tests for `python3 -m myflames`."""

    PYTHON = sys.executable
    SAMPLE = os.path.join(TEST_DIR, "mysql-explain-json-sample.json")
    JOIN = os.path.join(TEST_DIR, "mysql-explain-json-join.json")
    COMPLEX = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")
    # Complex 5-table aggregate: many stages, deep nesting (exercises all renderers fully)
    COMPLEX5T = os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")

    def _run(self, *args, input_text=None):
        cmd = [self.PYTHON, "-m", "myflames"] + list(args)
        result = subprocess.run(
            cmd,
            input=input_text,
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        return result

    def _assert_valid_svg_output(self, result, label=""):
        self.assertEqual(
            result.returncode, 0,
            f"{label}: exit code {result.returncode}\nstderr: {result.stderr}",
        )
        self.assertTrue(
            _is_valid_svg(result.stdout),
            f"{label}: stdout is not valid SVG\n"
            f"(starts with: {result.stdout[:80]!r})",
        )

    def test_flamegraph_default(self):
        r = self._run(self.SAMPLE)
        self._assert_valid_svg_output(r, "flamegraph default")

    def test_bargraph_type(self):
        r = self._run("--type", "bargraph", self.JOIN)
        self._assert_valid_svg_output(r, "bargraph")

    def test_treemap_type(self):
        r = self._run("--type", "treemap", self.COMPLEX)
        self._assert_valid_svg_output(r, "treemap")

    def test_diagram_type(self):
        r = self._run("--type", "diagram", self.COMPLEX)
        self._assert_valid_svg_output(r, "diagram")

    def test_tree_type(self):
        r = self._run("--type", "tree", self.COMPLEX)
        self._assert_valid_svg_output(r, "tree")

    @unittest.skipUnless(
        os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")),
        "complex 5-table fixture missing",
    )
    def test_flamegraph_complex_5t(self):
        r = self._run("--type", "flamegraph", self.COMPLEX5T)
        self._assert_valid_svg_output(r, "flamegraph complex 5-table")

    @unittest.skipUnless(
        os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")),
        "complex 5-table fixture missing",
    )
    def test_bargraph_complex_5t(self):
        r = self._run("--type", "bargraph", self.COMPLEX5T)
        self._assert_valid_svg_output(r, "bargraph complex 5-table")

    @unittest.skipUnless(
        os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")),
        "complex 5-table fixture missing",
    )
    def test_treemap_complex_5t(self):
        r = self._run("--type", "treemap", self.COMPLEX5T)
        self._assert_valid_svg_output(r, "treemap complex 5-table")

    @unittest.skipUnless(
        os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")),
        "complex 5-table fixture missing",
    )
    def test_diagram_complex_5t(self):
        r = self._run("--type", "diagram", self.COMPLEX5T)
        self._assert_valid_svg_output(r, "diagram complex 5-table")

    @unittest.skipUnless(
        os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")),
        "complex 5-table fixture missing",
    )
    def test_tree_complex_5t(self):
        r = self._run("--type", "tree", self.COMPLEX5T)
        self._assert_valid_svg_output(r, "tree complex 5-table")

    def test_stdin_input(self):
        with open(self.SAMPLE, encoding="utf-8") as f:
            content = f.read()
        r = self._run("-", input_text=content)
        self._assert_valid_svg_output(r, "stdin input")

    def test_invalid_file_exits_nonzero(self):
        r = self._run("/nonexistent/path/to/explain.json")
        self.assertNotEqual(r.returncode, 0)

    def test_invalid_json_exits_nonzero(self):
        r = self._run("-", input_text="not valid json")
        self.assertNotEqual(r.returncode, 0)

    def test_title_option(self):
        r = self._run("--title", "My Custom Title", "--type", "bargraph", self.SAMPLE)
        self._assert_valid_svg_output(r, "custom title")
        self.assertIn("My Custom Title", r.stdout)

    def test_inverted_flag(self):
        r = self._run("--inverted", self.SAMPLE)
        self._assert_valid_svg_output(r, "inverted flamegraph")

    def test_width_option(self):
        r = self._run("--width", "800", "--type", "bargraph", self.SAMPLE)
        self._assert_valid_svg_output(r, "custom width")

    def test_all_fixtures_flamegraph(self):
        """All discovered fixtures must produce a valid flamegraph without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run(fixture)
                # Some fixtures may have all-zero self-time; tolerate exit 1 with specific stderr
                if r.returncode != 0:
                    self.assertIn(
                        "all zero self-time",
                        r.stderr.lower(),
                        f"Unexpected failure for {fixture}:\n{r.stderr}",
                    )
                else:
                    self.assertTrue(_is_valid_svg(r.stdout))

    def test_all_fixtures_bargraph(self):
        """All discovered fixtures must produce a valid bargraph without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run("--type", "bargraph", fixture)
                self.assertEqual(r.returncode, 0, f"stderr: {r.stderr}")
                self.assertTrue(_is_valid_svg(r.stdout))

    def test_all_fixtures_diagram(self):
        """All discovered fixtures must produce a valid diagram without error."""
        for fixture in ALL_FIXTURES:
            with self.subTest(fixture=os.path.basename(fixture)):
                r = self._run("--type", "diagram", fixture)
                self.assertEqual(r.returncode, 0, f"stderr: {r.stderr}")
                self.assertTrue(_is_valid_svg(r.stdout))


# ---------------------------------------------------------------------------
# TestAnalysis — unit tests for analyze_plan() and render_analysis_panel()
# ---------------------------------------------------------------------------

class TestAnalysis(unittest.TestCase):
    """Tests for the plan analysis functions."""

    HASH_JOIN = os.path.join(TEST_DIR, "mysql-explain-hash-join.json")
    TABLE_SCAN = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
    MATERIALIZE = os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")
    COMPLEX = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")

    def _analyze(self, path):
        root = parse_explain(_load(path))
        return root, analyze_plan(root)

    # --- analyze_plan: hash join detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_detected(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertGreater(len(a["hash_joins"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_feature_flag(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("hash_join" in f for f in a["optimizer_features"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_warning_present(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("hash join" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_suggestion_present(self):
        _, a = self._analyze(self.HASH_JOIN)
        self.assertTrue(any("join_buffer_size" in s for s in a["suggestions"]))

    # --- analyze_plan: full table scan detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_detected(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertGreater(len(a["full_scans"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_has_table_name(self):
        _, a = self._analyze(self.TABLE_SCAN)
        for s in a["full_scans"]:
            self.assertIn("table", s)
            self.assertTrue(s["table"])

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_warning_present(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertTrue(any("full table scan" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_suggestion_present(self):
        _, a = self._analyze(self.TABLE_SCAN)
        self.assertTrue(len(a["suggestions"]) > 0)

    # --- analyze_plan: temp table (Materialize) detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_detected(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertGreater(len(a["temp_tables"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_warning_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("temp table" in w.lower() for w in a["warnings"]))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_suggestion_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("tmp_table_size" in s for s in a["suggestions"]))

    # --- analyze_plan: filesort detection ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_detected(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertGreater(len(a["filesorts"]), 0)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_warning_present(self):
        _, a = self._analyze(self.MATERIALIZE)
        self.assertTrue(any("sort" in w.lower() for w in a["warnings"]))

    # --- analyze_plan: nested loop / ICP features ---

    def test_nested_loop_feature_complex(self):
        _, a = self._analyze(self.COMPLEX)
        # complex join fixture uses nested loop joins
        features = a["optimizer_features"]
        # At least some features should be detected
        self.assertIsInstance(features, list)

    def test_icp_detection_when_pushed_index_condition(self):
        """Plans with pushed_index_condition should report ICP=on."""
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-035-join-2t-users-orders.json"))
        # This fixture has pushed_index_condition so ICP should appear
        features = a["optimizer_features"]
        self.assertTrue(any("index_condition_pushdown" in f for f in features))

    # --- analyze_plan: return structure ---

    def test_analyze_plan_returns_required_keys(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for key in ("full_scans", "hash_joins", "temp_tables", "filesorts",
                    "optimizer_features", "warnings", "suggestions", "node_highlights"):
            self.assertIn(key, a, f"Missing key: {key}")

    def test_analyze_plan_lists_are_lists(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for key in ("full_scans", "hash_joins", "temp_tables", "filesorts",
                    "optimizer_features", "warnings", "suggestions", "node_highlights"):
            self.assertIsInstance(a[key], list, f"{key} should be a list")

    def test_analyze_plan_strings_are_strings(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for w in a["warnings"]:
            self.assertIsInstance(w, str)
        for s in a["suggestions"]:
            self.assertIsInstance(s, str)
        for f in a["optimizer_features"]:
            self.assertIsInstance(f, str)

    def test_node_highlights_have_short_label_and_message(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        for h in a["node_highlights"]:
            self.assertIn("short_label", h)
            self.assertIn("message", h)
            self.assertIsInstance(h["short_label"], str)
            self.assertIsInstance(h["message"], str)

    # --- render_analysis_panel ---

    def test_render_analysis_panel_returns_tuple(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        result = render_analysis_panel(a, 0, 0, 1200)
        self.assertIsInstance(result, tuple)
        self.assertEqual(len(result), 2)

    def test_render_analysis_panel_lines_are_strings(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, h = render_analysis_panel(a, 0, 0, 1200)
        self.assertIsInstance(lines, list)
        for line in lines:
            self.assertIsInstance(line, str)

    def test_render_analysis_panel_positive_height(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        _, h = render_analysis_panel(a, 0, 0, 1200)
        self.assertGreater(h, 0)

    def test_render_analysis_panel_contains_rect(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, _ = render_analysis_panel(a, 10, 100, 800)
        svg = "\n".join(lines)
        self.assertIn("<rect", svg)
        self.assertIn("<text", svg)

    def test_render_info_panel_single_block(self):
        """Consolidated panel contains both 'How to read' and 'Query Analysis'."""
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, h = render_info_panel(a, 0, 0, 800, view_type="bargraph")
        svg = "\n".join(lines)
        self.assertIn("How to read", svg)
        self.assertIn("Query Analysis", svg)
        self.assertGreater(h, 0)

    # --- Renderer integration: analysis panel in SVG output ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_treemap_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_bargraph_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_diagram_with_analysis_is_valid_svg(self):
        root = parse_explain(_load(self.TABLE_SCAN))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertTrue(_is_valid_svg(svg))
        self.assertIn("Query Analysis", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_treemap_shows_warning(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertIn("hash join", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_bargraph_shows_warning(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertIn("hash join", svg.lower())

    # --- full_scans / hash_joins structure ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_full_scan_entries_have_rows_and_loops(self):
        _, a = self._analyze(self.TABLE_SCAN)
        for s in a["full_scans"]:
            self.assertIn("rows", s)
            self.assertIn("loops", s)
            self.assertIsInstance(s["rows"], (int, float))
            self.assertIsInstance(s["loops"], int)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_entries_have_rows(self):
        _, a = self._analyze(self.HASH_JOIN)
        for h in a["hash_joins"]:
            self.assertIn("rows", h)
            self.assertIsInstance(h["rows"], (int, float))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_hash_join_plan_has_two_full_scans(self):
        """Hash join fixture has table scan on users and on orders."""
        _, a = self._analyze(self.HASH_JOIN)
        tables = {s["table"] for s in a["full_scans"]}
        self.assertIn("users", tables)
        self.assertIn("orders", tables)
        self.assertGreaterEqual(len(a["full_scans"]), 2)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_temp_table_entries_have_rows(self):
        _, a = self._analyze(self.MATERIALIZE)
        for t in a["temp_tables"]:
            self.assertIn("rows", t)
            self.assertIsInstance(t["rows"], (int, float))

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_entries_have_rows(self):
        _, a = self._analyze(self.MATERIALIZE)
        for f in a["filesorts"]:
            self.assertIn("rows", f)
            self.assertIsInstance(f["rows"], (int, float))

    # --- optimizer_features: covering, semijoin, antijoin ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-016-covering-index-cat-price.json")), "fixture missing")
    def test_covering_index_feature_detected(self):
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-016-covering-index-cat-price.json"))
        self.assertTrue(
            any("covering" in f.lower() or "index_extensions" in f for f in a["optimizer_features"]),
            f"Expected covering/index_extensions in {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-047-semi-join-users-with-orders.json")), "fixture missing")
    def test_semijoin_fixture_analyzed_with_features(self):
        """Semijoin plan (Nested loop + Materialize) produces analysis with at least one feature (e.g. nested_loop, ICP)."""
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-047-semi-join-users-with-orders.json"))
        self.assertIsInstance(a["optimizer_features"], list)
        # Fixture has nested loop and pushed_index_condition; semijoin is in SQL text not in operation string
        self.assertGreater(
            len(a["optimizer_features"]), 0,
            f"Expected at least one optimizer feature: {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-050-anti-join-users-no-orders.json")), "fixture missing")
    def test_antijoin_feature_detected(self):
        _, a = self._analyze(os.path.join(TEST_DIR, "fixtures", "explain-050-anti-join-users-no-orders.json"))
        self.assertTrue(
            any("antijoin" in f.lower() for f in a["optimizer_features"]),
            f"Expected antijoin in {a['optimizer_features']}",
        )

    # --- render_analysis_panel edge cases ---

    def test_render_analysis_panel_empty_analysis(self):
        """Panel with no features/warnings/suggestions still renders 'None detected' and valid SVG."""
        a = {
            "full_scans": [],
            "hash_joins": [],
            "temp_tables": [],
            "filesorts": [],
            "optimizer_features": [],
            "warnings": [],
            "suggestions": [],
        }
        lines, h = render_analysis_panel(a, 0, 0, 800)
        svg = "\n".join(lines)
        self.assertIn("Query Analysis", svg)
        self.assertIn("None detected", svg)
        self.assertGreater(h, 0)
        self.assertIn("<rect", svg)

    def test_render_analysis_panel_position_reflected_in_output(self):
        root = parse_explain(_load(self.COMPLEX))
        a = analyze_plan(root)
        lines, _ = render_analysis_panel(a, 100, 200, 600)
        svg = "\n".join(lines)
        self.assertIn('x="100"', svg)
        self.assertIn('y="200"', svg)

    # --- filesort suggestion text ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-052-derived-table-top-spenders.json")), "fixture missing")
    def test_filesort_suggestion_contains_sort_buffer_or_index(self):
        _, a = self._analyze(self.MATERIALIZE)
        suggestions_text = " ".join(a["suggestions"]).lower()
        self.assertTrue(
            "sort_buffer_size" in suggestions_text or "ordered index" in suggestions_text or "filesort" in suggestions_text,
            f"Expected sort_buffer_size or ordered index or filesort in suggestions: {a['suggestions']}",
        )

    # --- CLI: flamegraph includes Query Analysis panel ---

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_bargraph_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "bargraph", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_treemap_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "treemap", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_diagram_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "diagram", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")), "fixture missing")
    def test_cli_flamegraph_includes_query_analysis(self):
        fixture = os.path.join(TEST_DIR, "fixtures", "explain-001-table-scan-users-no-filter.json")
        r = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "flamegraph", fixture],
            capture_output=True,
            text=True,
            cwd=REPO_DIR,
        )
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Query Analysis", r.stdout)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_with_analysis_hash_join_shows_suggestion(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertIn("join_buffer_size", svg)

    # --- BNL (Block Nested Loop) detection ---

    BNL = os.path.join(TEST_DIR, "mysql-explain-bnl.json")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_detected(self):
        """BNL plan with using_join_buffer=Block Nested Loop and access_type=table is detected."""
        _, a = self._analyze(self.BNL)
        self.assertGreater(len(a["bnl_nodes"]), 0, "Expected BNL nodes in analysis")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_feature_flag(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("block_nested_loop" in f for f in a["optimizer_features"]),
            f"Expected block_nested_loop in optimizer_features: {a['optimizer_features']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_warning_present(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("block nested" in w.lower() or "bnl" in w.lower() for w in a["warnings"]),
            f"Expected BNL warning: {a['warnings']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_suggestion_references_join_buffer_size(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("join_buffer_size" in s for s in a["suggestions"]),
            f"Expected join_buffer_size in suggestions: {a['suggestions']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_suggestion_mentions_hash_join_alternative(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(
            any("hash join" in s.lower() or "block_nested_loop" in s for s in a["suggestions"]),
            f"Expected hash join alternative mention in suggestions: {a['suggestions']}",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_node_highlight_created(self):
        _, a = self._analyze(self.BNL)
        self.assertTrue(len(a["node_highlights"]) > 0, "Expected node highlights for BNL nodes")
        for h in a["node_highlights"]:
            self.assertIn("short_label", h)
            self.assertIn("message", h)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_not_triggered_by_hash_join(self):
        """Hash join plan should not produce BNL detection."""
        _, a = self._analyze(self.HASH_JOIN)
        self.assertEqual(len(a["bnl_nodes"]), 0, "Hash join should not be flagged as BNL")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_bargraph_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_bargraph(root, analysis=a)
        self.assertIn("block nested", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_treemap_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_treemap(root, analysis=a)
        self.assertIn("block nested", svg.lower())

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-bnl.json")), "fixture missing")
    def test_bnl_diagram_includes_warning(self):
        root = parse_explain(_load(self.BNL))
        a = analyze_plan(root)
        svg = render_diagram(root, analysis=a)
        self.assertIn("block nested", svg.lower())


# ---------------------------------------------------------------------------
# TestTree — collapsible tree renderer
# ---------------------------------------------------------------------------

_COMPLEX5T = os.path.join(TEST_DIR, "fixtures", "explain-068-complex-5t-aggregate.json")
_HAS_COMPLEX5T = os.path.exists(_COMPLEX5T)


class TestTree(unittest.TestCase):
    """Tests for the collapsible tree renderer (output_tree.py)."""

    HASH_JOIN = os.path.join(TEST_DIR, "mysql-explain-hash-join.json")
    COMPLEX_JOIN = os.path.join(TEST_DIR, "mysql-explain-complex-join.json")

    def _svg(self, fixture, **kwargs):
        root = parse_explain(_load(fixture))
        a = analyze_plan(root)
        return render_tree(root, analysis=a, **kwargs)

    # ---- Structural validity ----

    def test_tree_valid_svg_simple(self):
        svg = self._svg(self.HASH_JOIN)
        self.assertTrue(_is_valid_svg(svg), "tree: simple fixture produced invalid SVG")

    def test_tree_valid_svg_complex_join(self):
        svg = self._svg(self.COMPLEX_JOIN)
        self.assertTrue(_is_valid_svg(svg), "tree: complex-join fixture produced invalid SVG")

    @unittest.skipUnless(_HAS_COMPLEX5T, "complex 5-table fixture missing")
    def test_tree_valid_svg_complex_5t(self):
        """Complex 5-table aggregate with multiple stages must produce valid SVG."""
        svg = self._svg(_COMPLEX5T)
        self.assertTrue(_is_valid_svg(svg), "tree: complex 5-table fixture produced invalid SVG")

    # ---- All nodes present ----

    def test_tree_contains_all_node_labels(self):
        root = parse_explain(_load(self.COMPLEX_JOIN))
        svg = render_tree(root)
        for node in flatten_nodes(root):
            label = (node.get("short_label") or "")[:20]
            if not label:
                continue
            escaped = label.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            self.assertTrue(
                label in svg or escaped in svg,
                f"tree: node label {label!r} missing from SVG",
            )

    @unittest.skipUnless(_HAS_COMPLEX5T, "complex 5-table fixture missing")
    def test_tree_complex_5t_all_node_labels(self):
        """All node labels from the 5-table aggregate must appear in the tree SVG."""
        root = parse_explain(_load(_COMPLEX5T))
        svg = render_tree(root)
        for node in flatten_nodes(root):
            label = (node.get("short_label") or "")[:20]
            if not label:
                continue
            escaped = label.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            self.assertTrue(
                label in svg or escaped in svg,
                f"tree 5t: node label {label!r} missing from SVG",
            )

    # ---- Depth-driven indentation ----

    def test_tree_deeper_nodes_have_greater_indent(self):
        """Deeper nodes must have a larger x-offset than shallower ones."""
        import re
        root = parse_explain(_load(self.COMPLEX_JOIN))
        rows = list(_flatten_with_depth_for_test(root))
        # Find two rows at different depths and compare x positions in the SVG
        svg = render_tree(root)
        # The label x = LEFT + depth * INDENT + TOGGLE_W; just verify depth data-attrs exist
        depths_in_svg = re.findall(r'data-depth="(\d+)"', svg)
        depths = [int(d) for d in depths_in_svg]
        self.assertGreater(max(depths), 0, "tree: all rows have depth 0 — no hierarchy")

    # ---- Interactive JS features ----

    def test_tree_has_collapse_expand_js(self):
        svg = self._svg(self.HASH_JOIN)
        self.assertIn("toggle(", svg, "tree: toggle JS missing")
        self.assertIn("collapseAll", svg, "tree: collapseAll JS missing")
        self.assertIn("expandAll", svg, "tree: expandAll JS missing")
        self.assertIn("reflow", svg, "tree: reflow JS missing")

    def test_tree_has_click_to_pin(self):
        svg = self._svg(self.HASH_JOIN)
        self.assertIn("pinnedBg", svg, "tree: click-to-pin JS missing")
        self.assertIn("details-l0", svg, "tree: pre-allocated details strip missing")

    def test_tree_has_ctrlf_search(self):
        svg = self._svg(self.HASH_JOIN)
        self.assertIn("searchPrompt", svg, "tree: Ctrl+F search JS missing")
        self.assertIn('key === "f"', svg, "tree: Ctrl+F keydown handler missing")

    # ---- Query Analysis panel ----

    def test_tree_has_query_analysis_panel(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        svg = render_tree(root, analysis=a)
        self.assertIn("Query Analysis", svg, "tree: Query Analysis panel missing")
        self.assertIn("How to read", svg, "tree: How to read section missing")

    @unittest.skipUnless(_HAS_COMPLEX5T, "complex 5-table fixture missing")
    def test_tree_complex_5t_has_query_analysis_panel(self):
        root = parse_explain(_load(_COMPLEX5T))
        a = analyze_plan(root)
        svg = render_tree(root, analysis=a)
        self.assertIn("Query Analysis", svg, "tree 5t: Query Analysis panel missing")

    # ---- data-info on every row ----

    def test_tree_rows_have_data_info(self):
        svg = self._svg(self.COMPLEX_JOIN)
        self.assertIn('data-info="', svg, "tree: no data-info attributes found on rows")

    @unittest.skipUnless(_HAS_COMPLEX5T, "complex 5-table fixture missing")
    def test_tree_complex_5t_rows_have_data_info(self):
        svg = self._svg(_COMPLEX5T)
        self.assertIn('data-info="', svg, "tree 5t: no data-info attributes on rows")


def _flatten_with_depth_for_test(node, depth=0):
    yield node, depth
    for child in node.get("children") or []:
        yield from _flatten_with_depth_for_test(child, depth + 1)


# ---------------------------------------------------------------------------
# TestDocumentation — README links, doc files, and interactive JS claims
# ---------------------------------------------------------------------------

class TestDocumentation(unittest.TestCase):
    """Validate that README-documented features and links match the actual project state."""

    DOCS_DEMOS = os.path.join(REPO_DIR, "docs", "demos")
    README_PATH = os.path.join(REPO_DIR, "README.md")
    HASH_JOIN = os.path.join(TEST_DIR, "mysql-explain-hash-join.json")

    def _readme(self):
        with open(self.README_PATH, encoding="utf-8") as f:
            return f.read()

    # ---- Documentation files exist ----

    def test_readme_exists(self):
        self.assertTrue(os.path.exists(self.README_PATH))

    def test_readme_referenced_doc_files_exist(self):
        """Every file/dir listed in the README Documentation table must exist."""
        refs = [
            "LEGACY-PERL.md",
            "docs/VISUAL_EXPLAIN_REFERENCE.md",
            "docs/prompts/",
            "test/README.md",
            "docs/cddl1.txt",
        ]
        for ref in refs:
            self.assertTrue(
                os.path.exists(os.path.join(REPO_DIR, ref)),
                f"README references {ref!r} but it does not exist",
            )

    # ---- Demo HTML links ----

    def test_readme_demo_html_files_exist_locally(self):
        """Every GitHub Pages demo URL in the README must have a matching local file."""
        import re
        readme = self._readme()
        linked = re.findall(
            r'\(https://vgrippa\.github\.io/myflames/demos/([^)]+\.html)\)', readme
        )
        self.assertGreater(len(linked), 0, "No demo HTML links found in README")
        for fname in linked:
            local = os.path.join(self.DOCS_DEMOS, fname)
            self.assertTrue(
                os.path.exists(local),
                f"README links to {fname!r} but docs/demos/{fname} does not exist",
            )

    # ---- CLI options match README ----

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_readme_all_four_output_types_work(self):
        """README documents 5 output types; all must succeed via CLI."""
        for t in ("flamegraph", "bargraph", "treemap", "diagram", "tree"):
            result = subprocess.run(
                [sys.executable, "-m", "myflames", "--type", t, self.HASH_JOIN],
                cwd=REPO_DIR, capture_output=True, text=True,
            )
            self.assertEqual(result.returncode, 0, f"--type {t} failed: {result.stderr[:300]}")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_readme_documented_cli_flags_work(self):
        """README-documented flags must not produce errors."""
        for extra in (
            ["--width", "1400", "--title", "Test Plan"],
            ["--no-enhance"],
            ["--type", "flamegraph", "--inverted"],
        ):
            result = subprocess.run(
                [sys.executable, "-m", "myflames"] + extra + [self.HASH_JOIN],
                cwd=REPO_DIR, capture_output=True, text=True,
            )
            self.assertEqual(result.returncode, 0, f"Flags {extra} failed: {result.stderr[:300]}")

    # ---- Interactive feature claims ----

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_bargraph_has_ctrlf_search(self):
        """README: Bar chart supports Ctrl+F search."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_bargraph(root)
        self.assertIn("searchPrompt", svg, "Ctrl+F search JS missing from bargraph")
        self.assertIn('key === "f"', svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_bargraph_has_click_to_pin(self):
        """README: Click bar pins the details."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_bargraph(root)
        self.assertIn("pinnedBar", svg, "Click-to-pin JS missing from bargraph")
        self.assertIn("details-l0", svg, "Pre-allocated details strip missing from bargraph")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_treemap_has_ctrlf_search(self):
        """README: Treemap supports Ctrl+F search."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_treemap(root)
        self.assertIn("searchPrompt", svg, "Ctrl+F search JS missing from treemap")
        self.assertIn('key === "f"', svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_treemap_has_breadcrumb(self):
        """Treemap must include a breadcrumb element that updates on zoom."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_treemap(root)
        self.assertIn('id="breadcrumb"', svg, "Breadcrumb element missing from treemap")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_has_scroll_zoom(self):
        """README: Diagram supports Ctrl+scroll-wheel zoom."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn("wheel", svg, "Scroll-wheel zoom JS missing from diagram")
        self.assertIn("svgYFromEvent", svg, "Diagram-area zoom guard missing")
        # Must require Ctrl so plain scroll can scroll the page
        self.assertIn("ctrlKey", svg, "Zoom must require Ctrl+wheel to allow page scrolling")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_zoom_does_not_block_page_scroll(self):
        """Wheel without Ctrl must not call preventDefault (page must be scrollable)."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        # The guard 'if (!e.ctrlKey && !e.metaKey) return;' must come before preventDefault
        # Verify the early-return guard precedes any preventDefault call
        ctrl_pos = svg.find("ctrlKey")
        prevent_pos = svg.find("preventDefault")
        self.assertGreater(ctrl_pos, 0, "ctrlKey guard not found")
        self.assertGreater(prevent_pos, 0, "preventDefault not found")
        self.assertLess(ctrl_pos, prevent_pos,
                        "ctrlKey guard must appear before preventDefault so plain scroll is not blocked")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_content_has_clip_path(self):
        """Diagram content must be clipped to the diagram area so zoom cannot overflow into the info panel."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn('id="diagram-clip"', svg, "diagram-clip clipPath definition missing")
        self.assertIn('clip-path="url(#diagram-clip)"', svg, "diagram-content must use the diagram-clip clipPath")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_has_drag_to_pan(self):
        """README: Diagram supports drag-to-pan."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn("mousedown", svg, "Drag-to-pan JS missing from diagram")
        self.assertIn("mousemove", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_has_dblclick_reset(self):
        """README: Double-click background resets zoom/pan in diagram."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn("dblclick", svg, "Double-click reset JS missing from diagram")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_has_click_to_pin(self):
        """README: Click node pins details in diagram."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn("pinned", svg, "Click-to-pin JS missing from diagram")
        self.assertIn("details-l0", svg, "Pre-allocated details strip missing from diagram")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_diagram_details_text_is_selectable(self):
        """README: Text in details strip is always selectable."""
        root = parse_explain(_load(self.HASH_JOIN))
        svg = render_diagram(root)
        self.assertIn("user-select: text", svg, "Details strip is not selectable in diagram")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_flamegraph_height_equals_viewbox(self):
        """Flamegraph height attribute must equal viewBox height to prevent clipping."""
        import re
        result = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "flamegraph", self.HASH_JOIN],
            cwd=REPO_DIR, capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, 0)
        svg = result.stdout
        m_h = re.search(r'height="(\d+)"', svg)
        m_vb = re.search(r'viewBox="0 0 \d+ (\d+)"', svg)
        self.assertIsNotNone(m_h, "height attribute missing from flamegraph SVG")
        self.assertIsNotNone(m_vb, "viewBox attribute missing from flamegraph SVG")
        self.assertEqual(
            int(m_h.group(1)), int(m_vb.group(1)),
            f"Flamegraph height ({m_h.group(1)}) != viewBox height ({m_vb.group(1)})",
        )

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_all_outputs_have_query_analysis_panel(self):
        """README: Every output type includes a Query Analysis panel."""
        from myflames.output_tree import render_tree
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        for label, svg in [
            ("bargraph", render_bargraph(root, analysis=a)),
            ("treemap", render_treemap(root, analysis=a)),
            ("diagram", render_diagram(root, analysis=a)),
            ("tree", render_tree(root, analysis=a)),
        ]:
            self.assertIn("Query Analysis", svg, f"Query Analysis panel missing from {label}")
            self.assertIn("How to read", svg, f"How to read section missing from {label}")

    # ---- GitHub Pages index and demo integrity ----

    def test_docs_index_html_exists(self):
        """docs/index.html must exist so https://vgrippa.github.io/myflames/ loads."""
        self.assertTrue(
            os.path.exists(os.path.join(REPO_DIR, "docs", "index.html")),
            "docs/index.html is missing — root GitHub Pages URL will return 404",
        )

    def test_docs_index_html_references_exist(self):
        """Every href/data in docs/index.html that points to demos/ must exist locally."""
        import re
        index_path = os.path.join(REPO_DIR, "docs", "index.html")
        if not os.path.exists(index_path):
            self.skipTest("docs/index.html does not exist")
        with open(index_path, encoding="utf-8") as f:
            content = f.read()
        refs = re.findall(r'(?:data|href)="(demos/[^"]+)"', content)
        self.assertGreater(len(refs), 0, "No demos/ references found in docs/index.html")
        for ref in refs:
            local = os.path.join(REPO_DIR, "docs", ref)
            self.assertTrue(
                os.path.exists(local),
                f"docs/index.html references '{ref}' but docs/{ref} does not exist",
            )

    def test_all_demo_html_files_reference_existing_svgs(self):
        """Every .html in docs/demos/ that embeds an SVG must have that SVG file present."""
        import re
        demos_dir = self.DOCS_DEMOS
        if not os.path.isdir(demos_dir):
            self.skipTest("docs/demos/ directory does not exist")
        html_files = [f for f in os.listdir(demos_dir) if f.endswith(".html")]
        self.assertGreater(len(html_files), 0, "No HTML files found in docs/demos/")
        for fname in sorted(html_files):
            html_path = os.path.join(demos_dir, fname)
            with open(html_path, encoding="utf-8") as f:
                content = f.read()
            svgs = re.findall(r'<object[^>]+data="([^"]+\.svg)"', content)
            for svg_ref in svgs:
                svg_path = os.path.join(demos_dir, svg_ref)
                self.assertTrue(
                    os.path.exists(svg_path),
                    f"docs/demos/{fname} references '{svg_ref}' which does not exist",
                )


# ---------------------------------------------------------------------------
# TestSQLAndIndexFeatures — format_sql, _suggest_indexes, CLI --query
# ---------------------------------------------------------------------------

class TestSQLAndIndexFeatures(unittest.TestCase):
    """Tests for SQL display and index-suggestion features."""

    LIKE_FIXTURE = os.path.join(TEST_DIR, "fixtures", "explain-022-filter-with-like.json")
    ICP_FIXTURE = os.path.join(TEST_DIR, "fixtures", "explain-019-filter-users-country-and-date.json")
    HASH_JOIN = os.path.join(TEST_DIR, "mysql-explain-hash-join.json")

    # ---- format_sql ----

    def test_format_sql_empty_returns_empty_list(self):
        self.assertEqual(format_sql(""), [])
        self.assertEqual(format_sql(None), [])

    def test_format_sql_strips_mysql_comment_prefix(self):
        sql = "/* select#1 */ SELECT id FROM users"
        lines = format_sql(sql)
        self.assertFalse(any("select#1" in l for l in lines), "Comment prefix not stripped")
        self.assertTrue(any("SELECT" in l.upper() for l in lines))

    def test_format_sql_removes_backtick_quoting(self):
        sql = "SELECT `users`.`id` FROM `users`"
        lines = format_sql(sql)
        combined = "\n".join(lines)
        self.assertNotIn("`", combined, "Backticks should be stripped")
        self.assertIn("users", combined)
        self.assertIn("id", combined)

    def test_format_sql_select_and_from_on_separate_lines(self):
        sql = "SELECT id, name FROM users WHERE id = 1"
        lines = format_sql(sql)
        upper = [l.upper().strip() for l in lines]
        self.assertTrue(any(l.startswith("SELECT") for l in upper), "No SELECT line")
        self.assertTrue(any(l.startswith("FROM") for l in upper), "No FROM line")

    def test_format_sql_where_on_own_line(self):
        sql = "SELECT id FROM users WHERE country = 'US'"
        lines = format_sql(sql)
        self.assertTrue(
            any(l.strip().upper().startswith("WHERE") for l in lines),
            "WHERE not on its own line",
        )

    def test_format_sql_order_by_on_own_line(self):
        sql = "SELECT id FROM users ORDER BY created_at LIMIT 10"
        lines = format_sql(sql)
        self.assertTrue(any(l.strip().upper().startswith("ORDER BY") for l in lines))
        self.assertTrue(any(l.strip().upper().startswith("LIMIT") for l in lines))

    def test_format_sql_join_indented(self):
        sql = "SELECT u.id FROM users u LEFT JOIN orders o ON u.id = o.user_id"
        lines = format_sql(sql)
        join_lines = [l for l in lines if "JOIN" in l.upper()]
        self.assertTrue(join_lines, "No JOIN line found")
        self.assertTrue(
            join_lines[0].startswith("  "),
            "JOIN line should be indented with 2 spaces",
        )

    def test_format_sql_real_mysql_fixture_query(self):
        """Query embedded in a real fixture should parse without errors."""
        import json
        with open(self.HASH_JOIN, encoding="utf-8") as f:
            raw = json.load(f)
        sql = raw.get("query", "")
        self.assertTrue(sql, "Fixture has no query field")
        lines = format_sql(sql)
        self.assertGreater(len(lines), 0)
        combined = "\n".join(lines)
        self.assertNotIn("select#1", combined.lower(), "Comment prefix not stripped from fixture query")

    # ---- _col_refs_for_table ----

    def test_col_refs_exact_table_name(self):
        cond = "(orders.created_at >= TIMESTAMP'2023-01-01')"
        cols = _col_refs_for_table(cond, "orders")
        self.assertIn("created_at", cols)

    def test_col_refs_alias_heuristic(self):
        """Single-char alias 'o' should resolve for table 'orders'."""
        cond = "(o.status = 'delivered')"
        cols = _col_refs_for_table(cond, "orders")
        self.assertIn("status", cols)

    def test_col_refs_empty_condition(self):
        self.assertEqual(_col_refs_for_table("", "orders"), [])
        self.assertEqual(_col_refs_for_table(None, "orders"), [])

    def test_col_refs_deduplicates(self):
        cond = "(users.name LIKE 'A%' OR users.name LIKE 'B%')"
        cols = _col_refs_for_table(cond, "users")
        self.assertEqual(cols.count("name"), 1, "Duplicate column should be deduped")

    # ---- _suggest_indexes ----

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-022-filter-with-like.json")), "fixture missing")
    def test_suggest_indexes_generates_ddl_for_table_scan_with_filter(self):
        root = parse_explain(_load(self.LIKE_FIXTURE))
        suggestions = _suggest_indexes(root)
        self.assertGreater(len(suggestions), 0, "Expected at least one index suggestion")
        ddl = suggestions[0]["ddl"]
        self.assertTrue(ddl.startswith("CREATE INDEX"), "DDL must start with CREATE INDEX")
        self.assertIn("ON users", ddl)
        self.assertIn("name", ddl)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-022-filter-with-like.json")), "fixture missing")
    def test_suggest_indexes_no_duplicates(self):
        root = parse_explain(_load(self.LIKE_FIXTURE))
        suggestions = _suggest_indexes(root)
        ddls = [s["ddl"] for s in suggestions]
        self.assertEqual(len(ddls), len(set(ddls)), "Duplicate DDL statements generated")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-019-filter-users-country-and-date.json")), "fixture missing")
    def test_suggest_indexes_no_suggestion_when_index_used(self):
        """No suggestion when the query already uses an index (no table scan)."""
        root = parse_explain(_load(self.ICP_FIXTURE))
        suggestions = _suggest_indexes(root)
        self.assertEqual(suggestions, [], "Should not suggest index when index already in use")

    # ---- analyze_plan() new keys ----

    def test_analyze_plan_always_has_index_suggestions_key(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        self.assertIn("index_suggestions", a)
        self.assertIsInstance(a["index_suggestions"], list)

    def test_analyze_plan_always_has_query_text_lines_key(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        self.assertIn("query_text_lines", a)
        self.assertIsInstance(a["query_text_lines"], list)

    # ---- render_info_panel with new sections ----

    def test_render_info_panel_shows_query_section_when_provided(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        a["query_text_lines"] = ["SELECT id", "FROM users"]
        panel_lines, _ = render_info_panel(a, 0, 0, 1200, view_type="diagram")
        svg = "\n".join(panel_lines)
        self.assertIn("Query", svg, "Query section header missing from panel")
        self.assertIn("SELECT id", svg)

    def test_render_info_panel_no_query_section_when_absent(self):
        root = parse_explain(_load(self.HASH_JOIN))
        a = analyze_plan(root)
        a["query_text_lines"] = []
        panel_lines, _ = render_info_panel(a, 0, 0, 1200, view_type="diagram")
        svg = "\n".join(panel_lines)
        # Should not have a Query section header band
        self.assertNotIn(">Query<", svg)

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-022-filter-with-like.json")), "fixture missing")
    def test_render_info_panel_shows_index_suggestions_section(self):
        root = parse_explain(_load(self.LIKE_FIXTURE))
        a = analyze_plan(root)
        # Ensure index_suggestions are populated
        self.assertGreater(len(a["index_suggestions"]), 0, "No index suggestions for like fixture")
        panel_lines, _ = render_info_panel(a, 0, 0, 1200, view_type="tree")
        svg = "\n".join(panel_lines)
        self.assertIn("Index suggestions", svg)
        self.assertIn("CREATE INDEX", svg)

    # ---- CLI --query and auto-extraction ----

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "fixtures", "explain-022-filter-with-like.json")), "fixture missing")
    def test_cli_auto_extracts_query_from_json(self):
        """SQL embedded in the EXPLAIN JSON should appear in the SVG output."""
        result = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "diagram", self.LIKE_FIXTURE],
            cwd=REPO_DIR, capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, 0)
        self.assertIn("Query", result.stdout, "Query section missing from auto-extracted output")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_cli_query_flag_overrides_json_query(self):
        """--query flag should appear in output and override JSON-embedded query."""
        result = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "tree",
             "--query", "SELECT sentinel_token FROM dual",
             self.HASH_JOIN],
            cwd=REPO_DIR, capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, 0)
        self.assertIn("sentinel_token", result.stdout, "--query text not found in SVG output")

    @unittest.skipUnless(os.path.exists(os.path.join(TEST_DIR, "mysql-explain-hash-join.json")), "fixture missing")
    def test_cli_index_suggestions_appear_in_output(self):
        """Fixture with filter + table scan should produce index suggestion DDL in SVG."""
        result = subprocess.run(
            [sys.executable, "-m", "myflames", "--type", "bargraph", self.LIKE_FIXTURE],
            cwd=REPO_DIR, capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, 0)
        self.assertIn("CREATE INDEX", result.stdout)


# ---------------------------------------------------------------------------
# MySQL 9.7 Hypergraph Optimizer tests
# ---------------------------------------------------------------------------

FIXTURES_DIR = os.path.join(TEST_DIR, "fixtures")

_HG_ON_CTE = os.path.join(FIXTURES_DIR, "explain-097-hypergraph-on-cte-window-rank.json")
_HG_OFF_CTE = os.path.join(FIXTURES_DIR, "explain-098-hypergraph-off-cte-window-rank.json")
_HG_ON_5T = os.path.join(FIXTURES_DIR, "explain-099-hypergraph-on-5t-avg-salary.json")
_HG_OFF_5T = os.path.join(FIXTURES_DIR, "explain-100-hypergraph-off-5t-avg-salary.json")
_HG_ON_CORR = os.path.join(FIXTURES_DIR, "explain-101-hypergraph-on-correlated-subquery.json")
_HG_ON_DEPT = os.path.join(FIXTURES_DIR, "explain-103-hypergraph-on-dept-summary.json")
_HG_ON_RANGE = os.path.join(FIXTURES_DIR, "explain-105-hypergraph-on-5t-salary-range.json")


class TestMySQL97QueryPlanWrapper(unittest.TestCase):
    """MySQL 9.7+ wraps EXPLAIN output in a query_plan key with json_schema_version."""

    @unittest.skipUnless(os.path.exists(_HG_ON_CTE), "fixture missing")
    def test_query_plan_wrapper_parsed(self):
        """Parser must unwrap the query_plan envelope from MySQL 9.7 JSON."""
        with open(_HG_ON_CTE) as f:
            root = parse_explain(f.read())
        self.assertNotEqual(root["short_label"], "unknown")
        self.assertGreater(root["total_time"], 0)

    @unittest.skipUnless(os.path.exists(_HG_ON_CTE), "fixture missing")
    def test_query_plan_wrapper_has_children(self):
        """Wrapped JSON must produce a tree with children, not a flat unknown node."""
        with open(_HG_ON_CTE) as f:
            root = parse_explain(f.read())
        self.assertGreater(len(root["children"]), 0)


class TestHypergraphFixtures(unittest.TestCase):
    """All MySQL 9.7 hypergraph fixtures must parse and render in all output types."""

    HG_FIXTURES = [
        f for f in sorted(glob.glob(os.path.join(FIXTURES_DIR, "explain-*hypergraph*.json")))
        if os.path.exists(f)
    ]

    def test_all_hypergraph_fixtures_parse(self):
        """Every hypergraph fixture must parse into a valid tree."""
        self.assertGreater(len(self.HG_FIXTURES), 0, "No hypergraph fixtures found")
        for path in self.HG_FIXTURES:
            with self.subTest(fixture=os.path.basename(path)):
                with open(path) as f:
                    root = parse_explain(f.read())
                self.assertNotEqual(root["short_label"], "unknown",
                                    f"Parser returned 'unknown' for {os.path.basename(path)}")
                self.assertGreater(root["total_time"], 0)

    def test_all_hypergraph_fixtures_flamegraph(self):
        """Every hypergraph fixture must produce a valid flamegraph."""
        for path in self.HG_FIXTURES:
            with self.subTest(fixture=os.path.basename(path)):
                result = subprocess.run(
                    [sys.executable, "-m", "myflames", path],
                    cwd=REPO_DIR, capture_output=True, text=True,
                )
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn("<svg", result.stdout)

    def test_all_hypergraph_fixtures_bargraph(self):
        """Every hypergraph fixture must produce a valid bargraph."""
        for path in self.HG_FIXTURES:
            with self.subTest(fixture=os.path.basename(path)):
                result = subprocess.run(
                    [sys.executable, "-m", "myflames", "--type", "bargraph", path],
                    cwd=REPO_DIR, capture_output=True, text=True,
                )
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn("<svg", result.stdout)

    def test_all_hypergraph_fixtures_treemap(self):
        """Every hypergraph fixture must produce a valid treemap."""
        for path in self.HG_FIXTURES:
            with self.subTest(fixture=os.path.basename(path)):
                result = subprocess.run(
                    [sys.executable, "-m", "myflames", "--type", "treemap", path],
                    cwd=REPO_DIR, capture_output=True, text=True,
                )
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn("<svg", result.stdout)

    def test_all_hypergraph_fixtures_diagram(self):
        """Every hypergraph fixture must produce a valid diagram."""
        for path in self.HG_FIXTURES:
            with self.subTest(fixture=os.path.basename(path)):
                result = subprocess.run(
                    [sys.executable, "-m", "myflames", "--type", "diagram", path],
                    cwd=REPO_DIR, capture_output=True, text=True,
                )
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn("<svg", result.stdout)


class TestHypergraphOnVsOff(unittest.TestCase):
    """Compare hypergraph=on vs hypergraph=off plan structures."""

    @unittest.skipUnless(os.path.exists(_HG_ON_CTE) and os.path.exists(_HG_OFF_CTE), "fixtures missing")
    def test_both_modes_parse_to_valid_trees(self):
        """Both hypergraph ON and OFF for the same query must parse successfully."""
        with open(_HG_ON_CTE) as f:
            root_on = parse_explain(f.read())
        with open(_HG_OFF_CTE) as f:
            root_off = parse_explain(f.read())
        self.assertNotEqual(root_on["short_label"], "unknown")
        self.assertNotEqual(root_off["short_label"], "unknown")
        self.assertGreater(root_on["total_time"], 0)
        self.assertGreater(root_off["total_time"], 0)

    @unittest.skipUnless(os.path.exists(_HG_ON_5T) and os.path.exists(_HG_OFF_5T), "fixtures missing")
    def test_5t_join_both_modes_have_children(self):
        """5-table join must produce multi-level trees in both optimizer modes."""
        with open(_HG_ON_5T) as f:
            root_on = parse_explain(f.read())
        with open(_HG_OFF_5T) as f:
            root_off = parse_explain(f.read())
        self.assertGreater(len(root_on["children"]), 0)
        self.assertGreater(len(root_off["children"]), 0)

    @unittest.skipUnless(os.path.exists(_HG_ON_5T), "fixture missing")
    def test_hypergraph_on_detects_hash_join(self):
        """Hypergraph optimizer is known to use hash joins; verify detection."""
        with open(_HG_ON_5T) as f:
            root = parse_explain(f.read())
        analysis = analyze_plan(root)
        # Hypergraph may use hash joins for multi-table queries
        all_labels = []
        def collect(n):
            all_labels.append(n["full_label"])
            for c in n["children"]:
                collect(c)
        collect(root)
        has_hash = any("hash" in l.lower() for l in all_labels)
        has_nested = any("nested" in l.lower() for l in all_labels)
        # At least one join type must be present
        self.assertTrue(has_hash or has_nested,
                        "Expected hash join or nested loop in hypergraph plan")

    @unittest.skipUnless(os.path.exists(_HG_ON_CORR), "fixture missing")
    def test_correlated_subquery_parses(self):
        """Correlated subquery with hypergraph must parse to a valid tree."""
        with open(_HG_ON_CORR) as f:
            root = parse_explain(f.read())
        self.assertNotEqual(root["short_label"], "unknown")
        self.assertGreater(root["total_time"], 0)


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    unittest.main(verbosity=2)
